#!/bin/bash

if [ "$1" == "--remove" ]; then
    if [ ! -f "/usr/bin/sodu" ]; then
        echo "sodu is already removed."
    else
        sudo rm -f /usr/bin/sodu
        echo "sodu has been removed."
    fi
else
    if [ -f "/usr/bin/sodu" ]; then
        echo "sodu is already installed."
    else
        chmod +x ./sodu
        sudo cp ./sodu /usr/bin/
        echo "sodu has been installed."
    fi
fi

exit
